# Generated by Django 5.2.7 on 2025-10-16 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_journal', '0002_alter_journal_pub_date_thoughts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thoughts',
            new_name='Thought',
        ),
    ]
