# Generated by Django 5.2.7 on 2025-10-16 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_journal', '0003_rename_thoughts_thought'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thought',
            old_name='entry',
            new_name='thought',
        ),
    ]
